# Exploring and clustering Toronto neighborhoods

## Part 2

In [2]:
import numpy as np
import pandas as pd

In [3]:
#importing geospatial information for the neighborhoods
df_geo = pd.read_csv('Geospatial_Coordinates.csv')
df_geo.head(10)

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476
5         M1J  43.744734 -79.239476
6         M1K  43.727929 -79.262029
7         M1L  43.711112 -79.284577
8         M1M  43.716316 -79.239476
9         M1N  43.692657 -79.264848

In [4]:
df_geo.shape

(103, 3)

In [6]:
#importing the dataframe for Toronto created in the first part
df = pd.read_csv('Toronto-table1.csv')
df.head(10)

  PostalCode           Borough                      Neighborhood
0        M3A        North York                         Parkwoods
1        M4A        North York                  Victoria Village
2        M5A  Downtown Toronto         Regent Park, Harbourfront
3        M6A        North York  Lawrence Manor, Lawrence Heights
4        M7A      Queen's Park     Ontario Provincial Government
5        M9A         Etobicoke                  Islington Avenue
6        M1B       Scarborough                    Malvern, Rouge
7        M3B        North York                   Don Mills North
8        M4B         East York   Parkview Hill, Woodbine Gardens
9        M5B  Downtown Toronto          Garden District, Ryerson

In [76]:
#appending latitude and longitude for the neighboorhood
latitude = []
longitude = []

for i in range(df.shape[0]):
    postal_code = df.PostalCode[i]
    
    temp = df_geo.loc[df_geo['Postal Code'] == postal_code].reset_index(drop=True)
    lat = temp['Latitude'][0]
    long = temp['Longitude'][0]
    latitude.append(lat)
    longitude.append(long)
    
df['Latitude'] = latitude
df['Longitude'] = longitude
df.head(10)
    
#print(len(latitude))
#print(len(longitude))

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Queen's Park,Ontario Provincial Government,43.662301,-79.389494
5,M9A,Etobicoke,Islington Avenue,43.667856,-79.532242
6,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
7,M3B,North York,Don Mills North,43.745906,-79.352188
8,M4B,East York,"Parkview Hill, Woodbine Gardens",43.706397,-79.309937
9,M5B,Downtown Toronto,"Garden District, Ryerson",43.657162,-79.378937

In [77]:
df.to_csv('Toronto-table2.csv',index=False)